FROM eclipse-temurin:21-jdk AS build

WORKDIR /home/app
ADD demo /home/app/demo
RUN cd demo && ./mvnw -Dmaven.test.skip=true clean package


FROM eclipse-temurin:21-jre

ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.33.1/opentelemetry-javaagent.jar opentelemetry-javaagent.jar

COPY --from=build /home/app/demo/target/demo-0.0.1-SNAPSHOT.jar app.jar

CMD ["java", "-javaagent:opentelemetry-javaagent.jar", "-jar", "app.jar"]
